[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/']

# See more config options https://github.com/gakonst/foundry/tree/master/config
